### PR TITLE
fixed Readi UI broken on Swap, KYC pages

### PR DESCRIPTION
**Pull request by kapildave07**
## Description

Please describe the purpose of this pull request.

## Changes

- fixed Readi UI broken on Swap, KYC pages

## Attached Links

1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1871
2. Documents:

## Checklist

- [x] Manual tests
- [x] The pull request doesn't affect existing feature

## For reviewers

- Ensure new code doesn't break existing features
- Reviewer shouldn't merge if there are pending unresolved comments

### CODE REVIEW

**Comment by thi-investax** [comment]
did you test with mobile @kapildave07 ? does it still loook good?

**Comment by kapildave07** [comment]
> loook

@thi-investax i just update the UI for mobile

**Comment by thi-investax** [comment]
ok next time can we please take care of the mobile view without my reminder? 

It's vital for a developer to do beyond what is given, in the task I don't mention mobile but you should always take it in consideration when working on a task, if you are not clear then can ask me or Kevin to confirm that whether we need to implement mobile support for that task

**Comment by kapildave07** [comment]
> ok next time can we please take care of the mobile view without my reminder?
> 
> It's vital for a developer to do beyond what is given, in the task I don't mention mobile but you should always take it in consideration when working on a task, if you are not clear then can ask me or Kevin to confirm that whether we need to implement mobile support for that task

@thi-investax okay got it

**Pull request merged**
