### PR TITLE
Fix links on unsuccessful deal

### PR DESCRIPTION
**Pull request by vflorea**

### CODE REVIEW

**Comment by vflorea** [comment]
+ https://app.clickup.com/t/4733323/IXS-2663

**Comment by vflorea** [comment]
`+https://app.clickup.com/t/4733323/IXS-2656`

**Comment by vflorea** [comment]
`+https://app.clickup.com/t/4733323/IXS-2673`

**Comment by vflorea** [comment]
`+https://app.clickup.com/t/4733323/IXS-2693`

**Review by witchaotic — APPROVED** [review]

**Pull request merged**
